---
# ··············································································
# ### Apache
# ··············································································

- name           : apache | Install Apache and its modules
  apt            :
    pkg          : "{{ item }}"
    state        : latest
  with_items     :
    - apache2
    - libapache2-mod-php

- name           : apache | Activate mod_rewrite
  apache2_module :
    name         : rewrite
    state        : present
  notify         :
    - Restart apache2

- name           : apache | Add user to group
  user           :
    name         : "{{ owner }}"
    groups       : www-data
    append       : yes

- name           : apache | Add folder html
  file           :
    path         : /home/vagrant/html
    state        : directory

- name           : apache | Remove folder html
  file           :
    path         : /var/www/html
    state        : absent

- name           : apache | Symlink html
  file           :
    src          : "/home/vagrant/html"
    dest         : "/var/www/html"
    state        : "link"
