---
# ··············································································
# ### Mysql
# ··············································································

- name                  : mysql | Install MySQL client, server and related libraries
  apt                   :
    pkg                 : "{{ item }}"
    state               : latest
  with_items            :
    - mysql-client
    - mysql-server
    - python-mysqldb

- name                  : mysql | Start MySQL service
  service               :
    name                : "mysql"
    state               : started
    enabled             : yes

- name                  : mysql | Setup MySQL creds for root user
  template              :
    src                 : "{{ mysqlTemplatePath }}"
    dest                : "/root/.my.cnf"
    owner               : "root"
    group               : "root"
    mode                : 0600

- name                  : mysql | Setup MySQL root password
  mysql_user            :
    name                : "root"
    password            : "{{ mysqlPass }}"
    host                : "{{ item }}"
    state               : present
    check_implicit_admin: yes
    priv                : "*.*:ALL,GRANT"
  with_items            :
    - 127.0.0.1
    - ::1
    - localhost
    - "%"

- name                  : mysql | Reload privilege tables
  command               : 'mysql -ne "{{ item }}"'
  with_items            :
    - GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
    - GRANT ALL PRIVILEGES ON *.* TO '{{ dbUser }}'@'%' IDENTIFIED BY '{{ dbPass }}' WITH GRANT OPTION;
    - FLUSH PRIVILEGES;
  changed_when: False

- name                  : mysql | Delete blank MySQL users
  mysql_user            :
    name                : ""
    host                : "{{ item }}"
    state               : absent
  with_items            :
    - 127.0.0.1
    - ::1
    - localhost

- name                  : mysql | Drop MySQL test database
  mysql_db              :
    name                : test
    state               : absent

- name                  : mysql | Setup empty database
  mysql_db              :
    name                : "{{ dbName }}"
    encoding            : "utf8"
    collation           : "utf8_unicode_ci"
    state               : "present"
    login_user          : "root"
    login_password      : "{{ mysqlPass }}"

- name                  : mysql | Setup MySQL user
  mysql_user            :
    name                : "{{ dbUser }}"
    password            : "{{ dbPass }}"
    host                : "localhost"
    priv                : "*.*:ALL"
    state               : "present"

- name                  :  mysql | Setup MySQL user
  lineinfile:
    dest                : /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp              : "^bind-address"
    line                : "# bind-address = 0.0.0.0"
  notify:
      - restart mysql
