---
# ··············································································
# ### Install PHP
# ··············································································

- name       : php | Install PHP and its modules
  apt        :
  pkg      : "{{ item }}"
  state    : latest
  with_items :
    - php7.1
    - php7.1-cgi
    - php7.1-cli
    - php7.1-curl
    - php7.1-gd
    - php7.1-intl
    - php7.1-json
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-zip
    - php-imagick
