---
# ··············································································
    # ### Set up virtual host
# ··············································································

- name      : virtualhost | Copy virtual host setup over
  template  :
    src     : "{{ vhostTemplatePath }}"
    dest    : /etc/apache2/sites-available/

- name      : virtualhost | Activate virtual host
  command   : a2ensite vhost

- name      : virtualhost | Deactivate default vhost
  command   : a2dissite 000-default

- name      : virtualhost | Ensure Apache is running
  service   :
    name    : apache2
    state   : restarted
    enabled : yes
