---

# ··············································································
    # ### Wordpress
# ··············································································

- name      : wordpress | Download WordPress
  get_url   :
    url     : https://wordpress.org/latest.zip
    dest    : "{{ wp_path }}/wordpress.zip"

- name      : wordpress | Unzip WordPress
  unarchive :
    src     : "{{ wp_path }}/wordpress.zip"
    dest    : "{{ wp_path }}"
    copy    : no

- name      : wordpress | Symlink web root to unzipped WordPress
  file      :
    src     : "{{ wp_path }}/wordpress"
    dest    : "/var/www/wordpress"
    state   : "link"

- name      : wordpress | Wordpress | set wp-config.php
  template  :
    src     : "{{ wordpressTemPath }}"
    dest    : "{{ wp_path }}/wordpress/"
    mode    : 0750

- name      : wordpress | Download All in one migration wordpress plugin
  get_url   :
    url     : https://downloads.wordpress.org/plugin/all-in-one-wp-migration.6.63.zip
    dest    : "{{ wp_path }}/all-in-one-wp-migration.zip"

- name      : wordpress | Unzip All in one migration wordpress plugin
  unarchive :
    src     : "{{ wp_path }}/all-in-one-wp-migration.zip"
    dest    : "{{ wp_path }}/wordpress//wp-content/plugins"
    copy    : no
