---
# ··············································································
    # ### Install WP-CLI
# ··············································································

- name    : wp-cli | Download wp-cli
  get_url :
    url   : https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest  : /usr/bin/wp

- name    : wp-cli | Make wp-cli executable
  file    :
    path  : /usr/bin/wp
    mode  : "u+rwx,g+rx,o+rx"
