---
# ··············································································
# ### Install zsh
# ··············································································

- name      : zsh | remove folders
  file      :
    state   : absent
    path    : "{{ item }}"
  with_items:
    - "{{ home }}/.zshrc"
    - "{{ home }}/.oh-my-zsh"
    - "{{ home }}/.antigen"
    - "{{ home }}/antigen.zshrc"
    - "{{ home }}/.zshrc"

# ··· Install ZSH
- name      : zsh | Install ZSH
  apt       :
    pkg     : zsh
    state   : latest

- name      : zsh | Set zsh as default shell
  user      :
    name    : "{{ owner }}"
    shell   : /bin/zsh


# ··· Install Oh-My-ZSH
- name      : zsh | Install Oh-My-ZSH
  git       :
    repo    : https://github.com/robbyrussell/oh-my-zsh.git
    dest    : "{{ home }}/.oh-my-zsh"

- name      : zsh | Install Oh-My-ZSH - Change permissions
  file      :
    path    : "{{ home }}/.oh-my-zsh"
    owner   : "{{ owner }}"
    group   : "{{ group }}"
    state   : directory
    recurse : yes


# ··· Create file .zshrc
- name      : zsh | Create file .zshrc
  template  :
    src     : "templates/zshrc"
    dest    : "{{ home }}/.zshrc"

- name      : zsh | Change .zshrc owner and group
  file      :
    path    : "{{ home }}/.zshrc"
    owner   : "{{ owner }}"
    group   : "{{ group }}"
    mode    : 0644

# ··· Install  zsh git prompt
- name      : zsh | Install zsh git prompt
  git       :
    repo    : https://github.com/Mayccoll-Forks/zsh-git-prompt.git
    dest    : "{{ home }}/.zsh-git-prompt"

- name      : zsh | Install zsh git prompt - Change permissions
  file      :
    path    : "{{ home }}/.zsh-git-prompt"
    owner   : "{{ owner }}"
    group   : "{{ group }}"
    state   : directory
    recurse : yes


# ··· Install Oh-My-ZSH Plugin
- name      : zsh | Install Syntax Higbhtlighting
  git       :
    repo    : https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest    : "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name      : zsh | Install Syntax Higbhtlighting - Change permissions
  file      :
    path    : "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    owner   : "{{ owner }}"
    group   : "{{ group }}"
    state   : directory
    recurse : yes

# ··· Install Terminal Fonts
- name      : zsh | Install Terminal Fonts
  git       :
    repo    : http://github.com/gabrielelana/awesome-terminal-fonts.git
    dest    : "{{ home }}/awesome-terminal-fonts"
    version : patching-strategy

- name      : zsh | Install Terminal Fonts - Change permissions
  file      :
    path    : "{{ home }}/awesome-terminal-fonts"
    owner   : "{{ owner }}"
    group   : "{{ group }}"
    state   : directory
    recurse : yes

- name      : zsh | Install Terminal Fonts - Copy Fonts
  shell     : "cp {{ home }}/awesome-terminal-fonts/patched/*.ttf /usr/local/share/fonts"

- name      : zsh | Install Terminal Fonts - Install fontconfig
  apt       :
    pkg     : fontconfig
    state   : latest

- name      : zsh | Install Terminal Fonts - Update cache
  shell     : fc-cache -fv

- name      : zsh | Install Terminal Fonts - Remove Folder
  file      :
    state   : absent
    path    : "{{ home }}/awesome-terminal-fonts"
